apiVersion: v1
kind: ConfigMap
metadata:
  name: facturezen-config
data:
  # Backend config
  DB_HOST: postgres-service
  DB_PORT: "5432"
  REDIS_URL: redis://redis-service:6379/0
  S3_ENDPOINT: http://minio-service:9000
  GOTENBERG_URL: http://gotenberg-service:3000
  API_URL: http://backend-service:8000
  
  # Frontend config
  NEXT_PUBLIC_API_URL: http://localhost:8000 # Since it's browser-side
