apiVersion: v1
kind: Secret
metadata:
  name: facturezen-secrets
type: Opaque
data:
  # Echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  POSTGRES_DB: ZmFjdHVyZXplbg==
  
  # MinIO root credentials
  MINIO_ROOT_USER: bWluaW9hZG1pbg==
  MINIO_ROOT_PASSWORD: bWluaW9hZG1pbg==
  
  # JWT Secret (Example)
  SECRET_KEY: c3VwZXJzZWNyZXRrZXk=
